//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.1.0'.
//
package com.presidium.smashtourney.dao.adapter;

import com.apollographql.apollo3.api.Adapter;
import com.apollographql.apollo3.api.Adapters;
import com.apollographql.apollo3.api.CustomScalarAdapters;
import com.apollographql.apollo3.api.json.JsonReader;
import com.apollographql.apollo3.api.json.JsonWriter;
import com.presidium.smashtourney.dao.EventsByTournamentQuery;

import java.io.IOException;

public enum EventsByTournamentQuery_VariablesAdapter implements Adapter<EventsByTournamentQuery> {
  INSTANCE;

  @Override
  public EventsByTournamentQuery fromJson(JsonReader reader,
      CustomScalarAdapters customScalarAdapters) throws IOException {
    throw new IllegalStateException("Input type used in output position");
  }

  @Override
  public void toJson(JsonWriter writer, CustomScalarAdapters customScalarAdapters,
      EventsByTournamentQuery value) throws IOException {
    writer.name("tournamentId");
    Adapters.StringAdapter.toJson(writer, customScalarAdapters, value.tournamentId);
  }
}
