//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.1.0'.
//
package com.presidium.smashtourney.dao.type;

import com.apollographql.apollo3.api.ObjectType;

import java.util.Collections;

/**
 * A standing indicates the placement of something within a container.
 */
public class Standing {
  public static ObjectType type = new ObjectType("Standing", Collections.emptyList(), Collections.emptyList());
}
