//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.1.0'.
//
package com.presidium.smashtourney.dao.type;

import com.apollographql.apollo3.api.ObjectType;

import java.util.Collections;

/**
 * A videogame
 */
public class Videogame {
  public static ObjectType type = new ObjectType("Videogame", Collections.emptyList(), Collections.emptyList());
}
