//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.1.0'.
//
package com.presidium.smashtourney.dao;

import com.apollographql.apollo3.api.CustomScalarType;

/**
 * The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
 */
public class GraphQLInt {
  public static CustomScalarType type = new CustomScalarType("Int", "java.lang.Integer");
}
