//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.1.0'.
//
package com.presidium.smashtourney.dao;

import com.apollographql.apollo3.api.ObjectType;

import java.util.Collections;

public class StandingConnection {
  public static ObjectType type = new ObjectType("StandingConnection", Collections.emptyList(), Collections.emptyList());
}
