//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.1.0'.
//
package com.presidium.smashtourney.dao.selections;

import com.apollographql.apollo3.api.CompiledArgument;
import com.apollographql.apollo3.api.CompiledField;
import com.apollographql.apollo3.api.CompiledListType;
import com.apollographql.apollo3.api.CompiledSelection;
import com.apollographql.apollo3.api.CompiledVariable;
import com.presidium.smashtourney.dao.type.Event;
import com.presidium.smashtourney.dao.type.GraphQLID;
import com.presidium.smashtourney.dao.type.GraphQLString;
import com.presidium.smashtourney.dao.type.Tournament;
import com.presidium.smashtourney.dao.type.Videogame;

import java.util.Arrays;
import java.util.List;

public class EventsByTournamentQuerySelections {
  private static List<CompiledSelection> videogame = Arrays.asList(
    new CompiledField.Builder("id", GraphQLID.type).build()
  );

  private static List<CompiledSelection> events = Arrays.asList(
    new CompiledField.Builder("name", GraphQLString.type).build(),
    new CompiledField.Builder("videogame", Videogame.type).selections(videogame).build(),
    new CompiledField.Builder("id", GraphQLID.type).build()
  );

  private static List<CompiledSelection> tournament = Arrays.asList(
    new CompiledField.Builder("id", GraphQLID.type).build(),
    new CompiledField.Builder("events", new CompiledListType(Event.type)).selections(events).build()
  );

  public static List<CompiledSelection> root = Arrays.asList(
    new CompiledField.Builder("tournament", Tournament.type).arguments(Arrays.asList(new CompiledArgument("id", new CompiledVariable("tournamentId"), false))).selections(tournament).build()
  );
}
