//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.1.0'.
//
package com.presidium.smashtourney.dao.selections;

import com.apollographql.apollo3.api.CompiledArgument;
import com.apollographql.apollo3.api.CompiledField;
import com.apollographql.apollo3.api.CompiledListType;
import com.apollographql.apollo3.api.CompiledSelection;
import com.apollographql.apollo3.api.ImmutableMapBuilder;
import com.presidium.smashtourney.dao.Entrant;
import com.presidium.smashtourney.dao.Event;
import com.presidium.smashtourney.dao.GraphQLID;
import com.presidium.smashtourney.dao.GraphQLInt;
import com.presidium.smashtourney.dao.GraphQLString;
import com.presidium.smashtourney.dao.Standing;
import com.presidium.smashtourney.dao.StandingConnection;

import java.util.Arrays;
import java.util.List;

public class EventStandingsQuerySelections {
  private static List<CompiledSelection> entrant = Arrays.asList(
    new CompiledField.Builder("id", GraphQLID.type).build(),
    new CompiledField.Builder("name", GraphQLString.type).build()
  );

  private static List<CompiledSelection> nodes = Arrays.asList(
    new CompiledField.Builder("placement", GraphQLInt.type).build(),
    new CompiledField.Builder("entrant", Entrant.type).selections(entrant).build()
  );

  private static List<CompiledSelection> standings = Arrays.asList(
    new CompiledField.Builder("nodes", new CompiledListType(Standing.type)).selections(nodes).build()
  );

  private static List<CompiledSelection> event = Arrays.asList(
    new CompiledField.Builder("id", GraphQLID.type).build(),
    new CompiledField.Builder("name", GraphQLString.type).build(),
    new CompiledField.Builder("standings", StandingConnection.type).arguments(Arrays.asList(new CompiledArgument("query", new ImmutableMapBuilder().put("perPage", 3).put("page", 1), false))).selections(standings).build()
  );

  public static List<CompiledSelection> root = Arrays.asList(
    new CompiledField.Builder("event", Event.type).arguments(Arrays.asList(new CompiledArgument("id", 78790, false))).selections(event).build()
  );
}
