//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.1.0'.
//
package com.presidium.smashtourney.dao.selections;

import com.apollographql.apollo3.api.CompiledArgument;
import com.apollographql.apollo3.api.CompiledField;
import com.apollographql.apollo3.api.CompiledListType;
import com.apollographql.apollo3.api.CompiledSelection;
import com.apollographql.apollo3.api.ImmutableMapBuilder;
import com.presidium.smashtourney.dao.type.GraphQLID;
import com.presidium.smashtourney.dao.type.GraphQLString;
import com.presidium.smashtourney.dao.type.Tournament;
import com.presidium.smashtourney.dao.type.TournamentConnection;

import java.util.Arrays;
import java.util.List;

public class TournamentsByVideogameQuerySelections {
  private static List<CompiledSelection> nodes = Arrays.asList(
    new CompiledField.Builder("id", GraphQLID.type).build(),
    new CompiledField.Builder("name", GraphQLString.type).build(),
    new CompiledField.Builder("slug", GraphQLString.type).build()
  );

  private static List<CompiledSelection> tournaments = Arrays.asList(
    new CompiledField.Builder("nodes", new CompiledListType(Tournament.type)).selections(nodes).build()
  );

  public static List<CompiledSelection> root = Arrays.asList(
    new CompiledField.Builder("tournaments", TournamentConnection.type).arguments(Arrays.asList(new CompiledArgument("query", new ImmutableMapBuilder().put("perPage", 3).put("page", 1).put("sortBy", "startAt asc").put("filter", new ImmutableMapBuilder().put("past", false).put("videogameIds", Arrays.asList(1))), false))).selections(tournaments).build()
  );
}
